services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    networks:
      - creator-awards-network

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    env_file: ./api/.env
    ports:
      - 5432:5432
    networks:
      - creator-awards-network
    depends_on:
      - redis

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - creator-awards-network
    volumes:
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - api

networks:
  creator-awards-network:
    driver: bridge

volumes:
  letsencrypt:
