services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: ./api/.env
    ports:
      - 5432:5432
    networks:
      - creator-awards-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - creator-awards-network
    volumes:
      - letsencrypt:/etc/letsencrypt

networks:
  creator-awards-network:
    driver: bridge

volumes:
  letsencrypt:
