services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - creator-awards-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - creator-awards-network

networks:
  creator-awards-network:
    driver: bridge
